title: "Fabrizio Ferrai"
description: "Software Engineer, <span class='nowrap'>Hacker, Consultant,</span><br/>Music lover, <span class='nowrap'>Clojurian</span>"
email: fabrizio@ferrai.io
disqus: "ferrai-io"
google-analytics-id: 'UA-46402862-5'
twitter: fabferrai
github: ff-
name: 'Fabrizio Ferrai'
author: 'Fabrizio Ferrai'

logo: "/assets/img/author.png"
author_image: "/assets/img/author.png"
bottom: "/assets/img/bottom.jpg"

url: "https://ff_.github.io"
baseurl: ""

social:
#  - icon: male
#    url:  "/about"
#    footer_desc: "Read a super long text about me"
  - icon:	twitter
    url:	https://twitter.com/fabferrai
    desc: "Follow me on twitter"
  - icon:	github-alt
    url:	https://github.com/ff-
    desc: "Follow me on github"
  - icon:	slideshare
    url:	https://slides.ferrai.io
  - icon:	briefcase
    url:	https://github.com/ff-/curriculum-vitae/raw/master/cv.pdf
    desc: "Curriculum Vitae"
    footer_desc: "Hiring? Grab CV!"
  - icon:	envelope-o
    url:	mailto:fabrizio@ferrai.io
    footer_desc: Let's chat about space, robots, and business

sharing:
  twitter:    true
  facebook:   true
  hn:         true
  reddit:     true

paginate:	10
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
