title: "Fabrizio Ferrai"
description: "&laquo;Insert smart quote here&raquo;<br/>Software Engineer, <span class='nowrap'>Consultant, Clojurian</span>"
email: fabrizio@ferrai.io
disqus: "ferrai-io"
google-analytics-id: 'UA-46402862-5'
twitter: fabferrai
github: ff-
name: 'Fabrizio Ferrai'
author: 'Fabrizio Ferrai'

logo: "/assets/img/author.png"
author_image: "/assets/img/author.png"
bottom: "/assets/img/bottom.jpg"

url: "https://ff_.github.io"
baseurl: ""

social:
#  - icon: male
#    url:  "/about"
#    footer_desc: "Read a super long text about me"
  - icon:	twitter
    url:	https://twitter.com/fabferrai
    desc: "Follow on Twitter!"
  - icon:	github-alt
    url:	https://github.com/ff-
    desc: "Follow on Github!"
  - icon:	slideshare
    url:	https://slides.ferrai.io
    desc: "In here there are some links in which I explain stuff to people and they actually get something"
  - icon:	magic
    url:	https://github.com/ff-/curriculum-vitae/raw/master/cv.pdf
    desc: "Curriculum Vitae"
    footer_desc: "Hiring? Grab CV!"
  - icon:	envelope-o
    url:	mailto:fabrizio@ferrai.io
    desc: "Yep, that's my email."
    footer_desc: Let's chat about space, robots, and business

sharing:
  twitter:    true
  facebook:   true
  hn:         true
  reddit:     true

paginate:	10
permalink: '/:year/:title/'
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
